ImpulsoGov/farolcovid

.gitignore
COVID19_App/app.py
COVID19_App/simulation.py
COVID19_App/style.css
README.md

first frontend pass, updated README

---

.gitignore
.vscode/settings.json
src/configs/scenario_parameters.yaml
src/model/seir.py
src/model/simulator.py
src/simulation.py

Run the simulator in `simulator.py` by calling `run_simulation`with args (in docstring) and get the dict with worst and best evolution dataframes.l
- Still need to add `calculate_dday` function

add worst and best cases simulator

---

src/model/simulator.py
src/simulation.py
src/style.css
src/utils.py

- Adicionando o primeiro caso na simulação para cidades sem nenhum caso
- Personalizando a seção do Simulador com texto e subtítulos

add fisrt city case + update simulator layout

---

src/model/simulator.py
src/simulation.py
src/style.css
src/team.py
src/utils.py

- Atualização da mensagem de WhatsApp
- Adição do primeiro caso para simulação de municípios sem casos confirmados
- Atualização do texto na seção do Simulador

Pequenas atualizações

---

src/model/simulator.py

- Priorizando quarentena para estratégias no mesmo dia

Atualização da simulação com a escolha das datas

---

src/configs/config.yaml
src/loader.py
src/model_description.py
src/simulation.py

* calculate active cases & recovered
* atualização da metodologia
* adiciona versionamento na metodologia
* consertando descricao de casos ativos
* mudando periodo considerado para severo + crítico & atualizando descricao dos estados iniciais com consideracoes

Calcula número de infectados ativos e recuperados inicial (#51)

---

.gitignore
src/configs/config.yaml
src/loader.py
src/simulation.py

Embaixadores names

---

analysis/subnotification.ipynb
analysis/themes/custom_colorscales.yaml
src/configs/config.yaml
src/loader.py
src/model/simulator.py
src/model_description.py
src/simulation.py
src/utils.py

Relacionado a #31 e #52 
- @JoaoCarabetta : pequenas correções: adicionei no output do modelo a data inicial do cálculo da projeção; mudei o nome da cor da paleta para ser usada direto no tema `custom`
- @ap1631 : da uma olhada  nas considerações iniciais do notebook `src/analysis/subnotifications.ipynb` :)

Adicionando análise de subnotificação e métrica de avaliação do modelo

---

src/model_description.py
src/simulation.py
src/team.py

Closes #31 
- Atualização do texto com nosso rascunho colaborativo (tinham várias modificações da @ap1631 que eu estava devendo ainda hehe)
- Adicionando descrição da taxa de subnotificação na metodologia 
@gabrielsaruhashi atualizei minha foto tambem, mudei no linkedin recentemente e tava quebrado o link ;)

Atualização da metolodogia

---

src/app.py

Muda o menu para 'radio'.
Penso que assim fica mais transparente o que o app oferece.

Muda o menu

---

src/model_description.py

não é urgente, só colocando para não esquecer

atualiza calculo de taxa de recuperacao

---

src/style.css
src/team.py

- Add Sarah e Paula no Programa de Embaixadores
- Add @victor-cortez e @francisconog  como devs voluntários
- Add descrição das instituições

Mais gente na turma!

---

README.md
analysis/README.md

Estamos crescendo! Mais pesquisador@s e devs querem fazer análises com os dados, então precisamos criar algumas regras para boa convivência e estabilidade das feerramentas.
- Todas as análises serão concentradas em `analysis` (obviamente) e devem seguir as instruções do [README](https://github.com/ImpulsoGov/simulacovid/blob/analysis-env/analysis/README.md)
closes #99

Criando ambiente para colaboração

---

Makefile

On the Makefile, "source" was yielding problems in Linux, so I added a if/else statement to use bin/bash on Linux and bin/sh elsewhere

Quick fix on the bin/bash used for compilation to better suit linux

---

src/configs/cities_table.csv
src/configs/states_table.csv
src/social_distancing_plots.py
src/utils.py

1- Added src/configs/cities_table.csv and src/configs/states_table.csv with the list of states and cities in our configs folder to helo us convert from frontend (Text) to backend (numerical id). It is very compact and contains only the key informations, so we can use it as a standard.
2- To convert use the new functions added  to src/utils.py :
In: id of a place (id < 100 for states, id > 100 for cities)
Out: either a string representing the name of the state or a list containing [state name,city name]
get_place_names_by_id(place_id)
In: name of the state (returns a numerical id of only the state) or the name of the state and the name of the city
Out: the numerical id of the state of the city
get_place_id_by_names(state_name, city_name_input="Todos")
3- Also added …

Id updated

---

src/pages/farolcovid.py
src/style.css
src/utils.py

gen_social_dist_plots_placeid(place_id, height=700) is the new function definition for the plot making script

Changed the plot to receive an optional height argument

---

src/model/simulator.py
src/pages/farolcovid.py
src/pages/plots.py
src/pages/simulacovid.py
src/session.py
src/utils.py

- Add "Update data" option to user
- Fix resource data
- Update description of sources

Update data from resources & other changes

---

src/configs/config.yaml
src/pages/farolcovid.py
src/pages/plots.py
src/pages/simulacovid.py
src/utils.py

- Fix resources number from NaN to zero, and readd available proportion of 50% - *now this change is made only to run the simulation and plot*
- Fix session update changing city/state: the data modified previously by user was not updated with the new choice - now it's working fine

Simulation & session fixes

---

src/models.py
src/pages/farolcovid.py

- Quick fix on capacity classification 
- Fix display text on cards

Fix capacity risk + change text

---

src/configs/config.yaml
src/model/simulator.py
src/pages/main.py
src/pages/simulacovid.py
src/utils.py

- Code cleaning: removing comments & useless calls to data (reduces loading time!)
- Fix random alterations on input changes
- Fix text on wpp msg

Minor fixes

---

src/configs/config.yaml
src/pages/main.py
src/pages/simulacovid.py
src/utils.py

- Update wpp msg
- New phone number
- Change ambassador program disclaimer
- Add new data paths to config

Updates on contact info & ambassador program

---

.gitignore
src/amplitude.py
src/pages/data_analysis.py
src/pages/main.py
src/pages/model_description.py
src/pages/risk_description.py
src/pages/rt_description.py
src/pages/simulacovid.py
src/pages/team.py
src/session.py
src/utils.py

Amplitude analytics

---

src/amplitude.py

Added new names (Now we have 53 and we do 3 pairs or 2 names)

Updated the hash function

---

src/plots.py

Some cities had a progressive order of data and some had a regressive one, so I added a sorting to organize it before calculating the mavg and plotting.

Correct the problems with mavg order

---

src/pages/main.py
src/session.py

I think we finally got it. (in colab w/ @victor-cortez )
- Using a new version of the `State`class implemented by [tvst](https://gist.github.com/tvst/0899a5cdc9f0467f7622750896e6bd7f) and working a lil bit, we manage to have a per-user unique session. This solves our issue with mixed users sessions when accessing the app at the same time!
- Basically, our `State` class now gets a user ID from _Streamlit_ on `session_info.session.id` and saves that key to a dictionary, accessing when the app is rerun to recognise each user session.
- *We've tested accessing on different devices - and it worked!*

Fix bug on user session! 🎉

---

src/configs/config.yaml

TODO:
- get health region url from Marco
- finish set up in API https://github.com/ImpulsoGov/coronacidades-datasource/pull/64

Add new reopening URLs

---

src/configs/config.yaml
src/farolcovid.py
src/pages/main.py
src/pages/saude_em_ordem.py
src/pages/saude_em_ordem_description.py
src/pdf_report/pdfgen.py
src/style.css

Added the main part of saúde em ordem after the initial farolcovid part
Added the metodology page for saúde em ordem
Modified the pdf download button to follow the design of our previous html buttons

First version of saude em ordem

---

requirements.txt
src/farolcovid.py
src/pages/main.py

It's hacking but it's working in my experiments.
Add the following env to `.env` file:
```ini
GOOGLE_ANALYTICS_CODE=UA-XXXXXXXX-X
```
I've created the branch from `stable` so I suggest testing and merging it directly to `stable`. Also, I need the current GA code to update the production environment.

Added support to Google Analytics

---

src/farolcovid.py
src/pages/main.py
src/pages/saude_em_ordem.py
src/resources/hide-iframes.html
src/resources/horizontalize-radio.html
src/resources/redo-button.html
src/resources/sidebar-closer.html
src/style.css
src/utils.py

Major changes to the UI:
- Redesign of the illustrative plot which was changed by a sequence of cards.
- Changes to the protocols at the end
- Redesign of the slider which was changed by a heavily hacked radio button group that was re-stylized to become vertical and bigger.
- Disabling of the "Baixar dados completos" button due to problems with google drive (to be solved later).
- The task bard now begins as closed in order to not mess with our design.
- The simula vs saude dropdown selection was changed to be made through 2 buttons (one in each card)
TODO:
1- Redesign streamlit buttons
2- Add health regions
2- Solve the google drive problem, which is that sometimes google blocks downloads from drive because it senses you are a robot downloading. Possible solutions: 1- Using a credential …

Saude Em Ordem Version 2

---

src/farolcovid.py
src/pages/main.py
src/resources/redo-button.html
src/resources/sidebar-closer.html
src/utils.py

Makes the simula vs saude card become clickable and therefore replace the dropdown selection.
Also makes the sidebar close while opening.

Card button

---

src/configs/config.yaml
src/farolcovid.py
src/pages/main.py
src/pdf_report/pdfgen.py
src/plots.py
src/utils.py

- Adapted inloco plot
- Rehabilitated pdf generation
- Corrected the config for saude em ordem data

Several fixes, enabling inloco plots and pdf generation

---

src/pages/saude_em_ordem.py
src/resources/saude-inverter.html

- Fixing full CSV table to download
- Correcting the order of weight selectors
- Adding methodology page

Quick fixes + Methodology page

---

src/pages/saude_em_ordem.py
src/plots.py

- Vital Strategies entered as our technical partner on Saude em Ordem 🤗
- Fix inloco plot - now it's appearing again, small fix on index :)

Fix inloco plot + Add partner on SeO! 🎉

---

src/configs/config.yaml
src/pages/main.py

- Heatmaps were broken with last update - fixing columns selection
- Add banner to new tool!

Add SeO banner + Fix heatmaps

---

src/helper-server/main.py
src/models.py
src/pages/main.py
src/pages/methodology.py

Add "/maps" no caminho
`http://datasource.coronacidades.org:5000/maps/map-iframe?place_id={map_place_id}`

Conserta o caminho do mapa

---

src/pages/main.py
src/pages/methodology.py
src/style.css
src/utils.py

@dandaramcsousa 
- Mudanças no texto
- Ajuste de botões

Ajustes fe farol v2

---

src/configs/config.yaml
src/pages/main.py
src/plots.py

- Linhas pontilhadas com os limites de classificação estavam desatualizadas --> agora puxam direto do `config`
- Pequenos ajustes textuais
UPDATE:
- Mostra estado selecionado primeiro no tabelão - contribuição da @gabriellearruda ❤️

Minor fix: Rt plot text & bounds

---

src/pages/main.py

Reverts ImpulsoGov/farolcovid#212

Revert "fixed tagmanager"

---

src/configs/config.yaml
src/pages/main.py

Update CNES + GTM

---

Makefile
src/pages/main.py
src/utils.py

Tarefa "Estruturar sistema de alerta de dados faltantes no FE".
Adiciona alerta para dois casos:
1.0 Quando todos os municípios de um Estado estiverem sem classificação, o banner aparece para o Estado
2.0 Quando não forem todos, coloca o banner como o nome da cidade selecionada.
**Mandar para stable se aprovado.**

Ga fealertupdate

---

Makefile
src/configs/config.yaml
src/models.py
src/pages/main.py
src/pages/risk_description.py
src/style.css
src/utils.py

Muda indicador de capacidade hospitalar: substituímos por ora a projeção de leitos por número de leitos UTI por 100mil habitantes
TODO:
Extra:
- Editei `make docker-build-dev` no Makefile para rodar o farol local numa rede `my-network` - isso serve para consertar o direcionamento do `localhost` quando quiser rodar API local
- Enxuguei o código da tabela de referência que estava repetido entre scripts para puxar de uma única função `gen_reference_table`

Capacity update

---

src/configs/config.yaml
src/models.py
src/pages/onda_covid.py

Oii Fe, para o OndaCovid eu fiz uma alteração no código para conseguir rodar o estado e o país, enquanto trabalhamos no agrupamento semanal da base, poderia olhar para mim por favor?

Fastfix ondacovid

---

src/pages/main.py

Reverts ImpulsoGov/farolcovid#236

Revert "Farol pesquisa"

---

src/loader.py
src/pages/main.py
src/pages/onda_covid.py

Reverts ImpulsoGov/farolcovid#240

Revert "Fix ondacity"
